apiVersion: v1
kind: ConfigMap
metadata:
  name: chunk-processor-config
data:
  AMQ_HOST: "amq-broker-hdls-svc"
  AMQ_PORT: "61616"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CONSUMER_CONCURRENCY: "1-10"
  SERVER_PORT: "8082"
