apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: chunk-processor-scaler
spec:
  scaleTargetRef:
    name: chunk-processor
  minReplicaCount: 2
  maxReplicaCount: 20
  triggers:
  - type: artemis-queue
    metadata:
      managementEndpoint: "amq-broker-hdls-svc:8161"
      queueName: "quantum.file.chunks"
      queueLength: "50"
      username: admin
      password: admin
